# Generated by Django 4.2 on 2023-04-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_message', models.CharField(max_length=800, null=True, unique=True)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AutoMessageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('q_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.automessage')),
            ],
        ),
        migrations.DeleteModel(
            name='FacebookUser',
        ),
    ]
