# Generated by Django 4.2 on 2023-04-27 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0002_automessage_automessagequestion_delete_facebookuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLinkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_message', models.CharField(max_length=800, null=True, unique=True)),
                ('title', models.CharField(help_text='title of the card', max_length=800)),
                ('imegs', models.ImageField(help_text='image for the card', upload_to='static/images')),
                ('link', models.CharField(default='https://ecargo.com.bd/', help_text='Enter Target Page Link Here To Redirect', max_length=800, null=True)),
                ('button_link', models.CharField(default='https://ecargo.com.bd/', help_text='Enter Target Page Link Here To Redirect. this can be diffrent from the above link.', max_length=800, null=True)),
                ('button_name', models.CharField(default='Visit Now', help_text='Button show this text on it', max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutoLinkMessageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=800, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('q_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.autolinkmessage')),
            ],
        ),
    ]
