# Generated by Django 4.2 on 2023-04-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0003_autolinkmessage_autolinkmessagequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='autolinkmessage',
            name='subtitle',
            field=models.CharField(help_text='Subtitle of the card', max_length=800, null=True),
        ),
    ]
