# Generated by Django 4.2 on 2023-04-27 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0004_autolinkmessage_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_message', models.CharField(max_length=800, null=True, unique=True)),
                ('text', models.CharField(help_text='title of the card', max_length=800)),
                ('button_link', models.CharField(default='https://ecargo.com.bd/', help_text='Enter Target Page Link Here To Redirect. this can be diffrent from the above link.', max_length=800, null=True)),
                ('button_name', models.CharField(default='Visit Now', help_text='Button show this text on it', max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkMessageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=800, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('q_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.autolinkmessage')),
            ],
        ),
    ]
