# Generated by Django 4.2 on 2023-04-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0005_linkmessage_linkmessagequestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkMessage',
            new_name='ButtonLinkMessage',
        ),
        migrations.RenameModel(
            old_name='LinkMessageQuestion',
            new_name='ButtonLinkMessageQuestion',
        ),
    ]
