# Generated by Django 4.2 on 2023-04-27 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0006_rename_linkmessage_buttonlinkmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonlinkmessagequestion',
            name='q_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.buttonlinkmessage'),
        ),
    ]
