# Generated by Django 4.2.5 on 2024-02-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0009_extra_quick_replays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalbtnlink',
            options={'verbose_name': 'Automated Button Message Link Answers', 'verbose_name_plural': 'Automated Button Message Link Answers'},
        ),
        migrations.AlterModelOptions(
            name='autolinkmessage',
            options={'verbose_name': 'Automated Message Link & Image Answers', 'verbose_name_plural': 'Automated Message Link & Image Answers'},
        ),
        migrations.AlterModelOptions(
            name='autolinkmessagequestion',
            options={'verbose_name': 'Automated Message Link Questions', 'verbose_name_plural': 'Automated Message Link Questions'},
        ),
        migrations.AlterModelOptions(
            name='automessage',
            options={'verbose_name': 'Automated Messages', 'verbose_name_plural': 'Automated Messages'},
        ),
        migrations.AlterModelOptions(
            name='automessagequestion',
            options={'verbose_name': 'Automated Message Questions', 'verbose_name_plural': 'Automated Message Questions'},
        ),
        migrations.AlterModelOptions(
            name='buttonlinkmessage',
            options={'verbose_name': 'Automated Button Message Link Questions', 'verbose_name_plural': 'Automated Button Message Link Questions'},
        ),
        migrations.AlterModelOptions(
            name='buttonlinkmessagequestion',
            options={'verbose_name': 'Automated Button Message Link Questions', 'verbose_name_plural': 'Automated Button Message Link Questions'},
        ),
        migrations.AlterModelOptions(
            name='extra_quick_replays',
            options={'verbose_name': 'Automated Extra quicks replays', 'verbose_name_plural': 'Automated Extra quicks replays'},
        ),
    ]
